theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
menubar: false
toolbar:
  [ undo redo | styleselect | alignleft aligncenter alignright | fullscreen ]
language:
  - ja
plugins:
  - table
  - fullscreen